name: DevOps Lab - Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Verify Java version
      run: java -version

    - name: Verify Maven version
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install --batch-mode

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: JAR
        path: target/*.jar
